apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: zipkin-cron
  labels:
    name: zipkin-cron
  namespace: sock-shop
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: zipkin-cron
            image: openzipkin/zipkin-dependencies:1.4.0
            env:
            - name: STORAGE_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: zipkin-mysql
            - name: MYSQL_USER
              value: zipkin
            - name: MYSQL_PASS
              value: zipkin
          restartPolicy: OnFailure

